export const LANGS = { en: 'English', ar: 'العربية', ary: 'الدارجة المغربية', fr: 'Français', es: 'Español' } as const;
export type Lang = keyof typeof LANGS;
export const TTS: Record<Lang, string> = { en: 'en-US', ar: 'ar-SA', ary: 'ar-MA', fr: 'fr-FR', es: 'es-ES' };
export const AI_LANG: Record<Lang, string> = { en: 'English', ar: 'Modern Standard Arabic', ary: 'Moroccan Darija (natural spoken Moroccan Arabic, Arabic script, not a literal translation)', fr: 'French', es: 'Spanish' };
type D = Record<'take'|'analyze'|'retake'|'prev'|'next'|'repeat'|'listen'|'helpful'|'yes'|'no'|'wrong'|'send'|'thanks'|'step'|'history'|'logout'|'manual', string>;
export const T: Record<Lang, D> = {
  en: { take: 'Take or upload a photo', analyze: 'Analyze', retake: 'Retake', prev: 'Previous', next: 'Next', repeat: 'Repeat', listen: 'Listen', helpful: 'Was this helpful?', yes: 'Yes', no: 'No', wrong: 'What was wrong?', send: 'Send', thanks: 'Thanks!', step: 'Step', history: 'History', logout: 'Log out', manual: 'Please check the official manual or ask a qualified professional.' },
  ar: { take: 'التقط صورة أو ارفعها', analyze: 'تحليل', retake: 'إعادة التصوير', prev: 'السابق', next: 'التالي', repeat: 'إعادة', listen: 'استمع', helpful: 'هل كان هذا مفيدًا؟', yes: 'نعم', no: 'لا', wrong: 'ما الخطأ؟', send: 'إرسال', thanks: 'شكرًا!', step: 'الخطوة', history: 'السجل', logout: 'تسجيل الخروج', manual: 'يرجى مراجعة الدليل الرسمي أو استشارة مختص.' },
  ary: { take: 'صوّر ولا شارجي تصويرة', analyze: 'حلّل', retake: 'عاود صوّر', prev: 'اللور', next: 'اللي موراه', repeat: 'عاود', listen: 'سمع', helpful: 'واش هادشي عاونك؟', yes: 'اه', no: 'لا', wrong: 'أشنو كان غالط؟', send: 'صيفط', thanks: 'شكرا!', step: 'المرحلة', history: 'التاريخ', logout: 'خروج', manual: 'شوف الدليل الرسمي ولا سول شي واحد مختص.' },
  fr: { take: 'Prendre ou importer une photo', analyze: 'Analyser', retake: 'Reprendre', prev: 'Précédent', next: 'Suivant', repeat: 'Répéter', listen: 'Écouter', helpful: 'Était-ce utile ?', yes: 'Oui', no: 'Non', wrong: "Qu'est-ce qui n'allait pas ?", send: 'Envoyer', thanks: 'Merci !', step: 'Étape', history: 'Historique', logout: 'Déconnexion', manual: 'Consultez le manuel officiel ou un professionnel qualifié.' },
  es: { take: 'Toma o sube una foto', analyze: 'Analizar', retake: 'Repetir', prev: 'Anterior', next: 'Siguiente', repeat: 'Repetir', listen: 'Escuchar', helpful: '¿Te ayudó?', yes: 'Sí', no: 'No', wrong: '¿Qué falló?', send: 'Enviar', thanks: '¡Gracias!', step: 'Paso', history: 'Historial', logout: 'Cerrar sesión', manual: 'Consulta el manual oficial o a un profesional cualificado.' },
};
